// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SyncResult reports what a catalog sync did.
 */
export interface SyncResult {
    "source": string;
    "models": number;
    "skipped": number;
}
