// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService owns the process lifecycle: it starts the scan loop when the application is
 * up, and reports startup warnings exactly once.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * Version returns the build version, for the about panel.
 */
export function Version(): $CancellablePromise<string> {
    return $Call.ByID(945157116);
}

/**
 * Warnings returns startup warnings (for example an unusable timezone) so the UI can show
 * them instead of them being lost in a log file.
 */
export function Warnings(): $CancellablePromise<string[] | null> {
    return $Call.ByID(1080663773);
}
