// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DashboardService serves every aggregate the charts need. All of it is read from the
 * precomputed rollups, except where a range cannot be answered by a day-keyed aggregate
 * (see store.pickSource), so a page render never scans the event table.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../store/models.js";

/**
 * Breakdown groups the range by one dimension. Accepted dimensions: harness, model,
 * project, agentType, outcome, costSource.
 */
export function Breakdown(q: store$0.RangeQuery, dim: string, limit: number): $CancellablePromise<store$0.BreakdownRow[] | null> {
    return $Call.ByID(3006359798, q, dim, limit);
}

/**
 * Compare aggregates the range and the adjacent previous window of equal length, which is
 * what the delta badges are computed from.
 */
export function Compare(q: store$0.RangeQuery): $CancellablePromise<store$0.Comparison> {
    return $Call.ByID(2071309770, q);
}

/**
 * Dims returns the dimension names the breakdown endpoints accept, so the UI does not have
 * to hardcode them.
 */
export function Dims(): $CancellablePromise<string[] | null> {
    return $Call.ByID(2120955840);
}

/**
 * Heatmap returns per-day totals across a window.
 */
export function Heatmap(fromMs: number, toMs: number): $CancellablePromise<store$0.HeatCell[] | null> {
    return $Call.ByID(2939401773, fromMs, toMs);
}

/**
 * Latency returns events that carry timing, newest first. Only OpenCode and omp record
 * timings, so the caller must present coverage rather than treating missing rows as zero.
 */
export function Latency(q: store$0.RangeQuery, limit: number): $CancellablePromise<store$0.LatencyPoint[] | null> {
    return $Call.ByID(4097671411, q, limit);
}

/**
 * Realtime returns per-minute buckets and active sessions for the last `minutes`.
 */
export function Realtime(minutes: number): $CancellablePromise<store$0.RealtimeSnapshot> {
    return $Call.ByID(3359092950, minutes);
}

/**
 * Series returns a time series at the requested granularity (hour, day, week or month).
 * Buckets with no usage are omitted and the frontend fills the axis from the range it asked
 * for; the result names the granularity it was actually built at, which can be coarser than
 * the request when an hourly chart would be unreadable.
 */
export function Series(q: store$0.RangeQuery, granularity: string): $CancellablePromise<store$0.SeriesResult> {
    return $Call.ByID(2469022354, q, granularity);
}

/**
 * Stacked returns (day, dimension value) cells for a stacked chart, keeping only the
 * largest `top` values so the legend is stable across days.
 */
export function Stacked(q: store$0.RangeQuery, dim: string, top: number): $CancellablePromise<store$0.StackedPoint[] | null> {
    return $Call.ByID(1364935700, q, dim, top);
}

/**
 * Totals aggregates the range.
 */
export function Totals(q: store$0.RangeQuery): $CancellablePromise<store$0.Totals> {
    return $Call.ByID(4246156744, q);
}

/**
 * UnpricedModels lists models with usage but no price, so the UI can offer to add a rate
 * instead of leaving a blank in the cost column.
 */
export function UnpricedModels(): $CancellablePromise<string[] | null> {
    return $Call.ByID(1319947157);
}
