// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../store/models.js";

/**
 * PricingSyncedPayload reports the outcome of a catalog sync.
 */
export interface PricingSyncedPayload {
    "source": string;
    "models": number;
    "skipped": number;
}

/**
 * SessionDetail is one session plus what it spent, for the drill-down panel.
 */
export interface SessionDetail {
    "session": store$0.Session;
    "totals": store$0.Totals;
    "byModel": store$0.BreakdownRow[] | null;
}

/**
 * SyncStatus describes the scan loop's schedule. It is separate from the state event
 * because the schedule is pulled on demand rather than pushed on every change.
 */
export interface SyncStatus {
    "running": boolean;
    "nextRunAt": number;
    "intervalMs": number;
    "burst": boolean;
}
