// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SleepService exposes the sleep controller and today's usage to the UI and the menu bar.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sleep$0 from "../sleep/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../store/models.js";

/**
 * AgentActive reports whether an agent is working right now, independently of the
 * auto-sleep setting. The menu bar asks for confirmation before an explicit sleep when it
 * returns true.
 */
export function AgentActive(): $CancellablePromise<boolean> {
    return $Call.ByID(1048473819);
}

/**
 * ClamshellSupported reports whether the platform can keep the machine running with the
 * lid closed beyond AC power. Only macOS can, through an administrator prompt.
 */
export function ClamshellSupported(): $CancellablePromise<boolean> {
    return $Call.ByID(1282718077);
}

/**
 * DisplaySleepNow turns the display off now without suspending the machine.
 */
export function DisplaySleepNow(): $CancellablePromise<void> {
    return $Call.ByID(3073358699);
}

/**
 * RequestClamshell raises the one administrator prompt needed to keep the machine running
 * with the lid closed. It is only ever called from an explicit user action.
 */
export function RequestClamshell(): $CancellablePromise<void> {
    return $Call.ByID(1234323450);
}

/**
 * RestoreClamshell undoes RequestClamshell, restoring the system's own lid behaviour.
 */
export function RestoreClamshell(): $CancellablePromise<void> {
    return $Call.ByID(1234382103);
}

/**
 * ScreensaverNow switches the session to the screensaver now.
 */
export function ScreensaverNow(): $CancellablePromise<void> {
    return $Call.ByID(4223286675);
}

/**
 * SleepNow puts the machine to sleep immediately. The menu bar asks for confirmation first
 * when an agent is still working; the service itself only carries out the request.
 */
export function SleepNow(): $CancellablePromise<void> {
    return $Call.ByID(275069061);
}

/**
 * Status reports the controller state. With no controller (a build without the desktop
 * window) it reports the feature as unsupported rather than erroring.
 */
export function Status(): $CancellablePromise<sleep$0.Status> {
    return $Call.ByID(1569099482);
}

/**
 * Today returns today's token totals in the configured timezone, for the menu bar's usage
 * section and any UI status line.
 */
export function Today(): $CancellablePromise<store$0.Totals> {
    return $Call.ByID(4283532713);
}
