// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SyncService exposes the scan loop to the UI: its status, a manual trigger, a cancel, and
 * the run history.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../store/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sync$0 from "../sync/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Cancel stops an in-flight scan. The next scan resumes from the stored cursors, so only
 * the work since the last committed batch is repeated.
 */
export function Cancel(): $CancellablePromise<boolean> {
    return $Call.ByID(1970541722);
}

/**
 * History returns the most recent scans, newest first.
 */
export function History(limit: number): $CancellablePromise<store$0.SyncRun[] | null> {
    return $Call.ByID(649243448, limit);
}

/**
 * LastRun returns the previous scan's summary, or a zero value before the first scan.
 */
export function LastRun(): $CancellablePromise<sync$0.RunSummary> {
    return $Call.ByID(1785426469);
}

/**
 * Status reports whether a scan is running and when the next one starts.
 */
export function Status(): $CancellablePromise<$models.SyncStatus> {
    return $Call.ByID(3480999138);
}

/**
 * TriggerNow starts an immediate scan. It returns false when one is already running.
 */
export function TriggerNow(): $CancellablePromise<boolean> {
    return $Call.ByID(2947274884);
}
