// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as service$0 from "../../../../vietlubu/agents-dashboard/internal/service/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as store$0 from "../../../../vietlubu/agents-dashboard/internal/store/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as sync$0 from "../../../../vietlubu/agents-dashboard/internal/sync/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "data:changed": sync$0.DataChangedEvent;
            "pricing:synced": service$0.PricingSyncedPayload;
            "settings:saved": store$0.Settings;
            "sync:done": sync$0.DoneEvent;
            "sync:error": sync$0.ErrorEvent;
            "sync:progress": sync$0.ProgressEvent;
            "sync:state": sync$0.StateEvent;
        }
    }
}
