// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BreakdownRow is one row of a grouped breakdown.
 */
export interface BreakdownRow {
    "key": string;
    "input": number;
    "output": number;
    "cacheRead": number;
    "cacheWrite": number;
    "reasoning": number;
    "total": number;
    "costUsd": number;
    "events": number;
    "latencyAvgMs": number;
    "latencyCount": number;
}

/**
 * Comparison is a current window against the adjacent previous window of equal length.
 */
export interface Comparison {
    "current": Totals;
    "previous": Totals;
}

/**
 * EventPage is a paged slice of events and the total matching count.
 */
export interface EventPage {
    "rows": EventRow[] | null;
    "total": number;
}

/**
 * EventRow is one row of the events table.
 */
export interface EventRow {
    "id": number;
    "harness": string;
    "ts": number;
    "localDay": string;
    "project": string;
    "sessionId": string;
    "model": string;
    "provider": string;
    "agentType": string;
    "agentName": string;
    "outcome": string;
    "input": number;
    "output": number;
    "cacheRead": number;
    "cacheWrite": number;
    "reasoning": number;
    "total": number;
    "costUsd": number | null;
    "costSource": string;
    "latencyMs": number | null;
    "ttftMs": number | null;
}

/**
 * ExportResult carries a rendered export back to the frontend, which turns it into a
 * download. Returning content (instead of writing a file) keeps export working in
 * headless server mode, where native save dialogs do not exist.
 */
export interface ExportResult {
    "filename": string;
    "mimeType": string;
    "content": string;
    "rows": number;

    /**
     * Truncated is true when the export hit the row cap.
     */
    "truncated": boolean;
}

/**
 * FacetValue is one selectable filter value with its event count.
 */
export interface FacetValue {
    "value": string;
    "events": number;
    "total": number;
}

/**
 * HarnessInfo describes a harness for the UI (id, label, availability, roots).
 */
export interface HarnessInfo {
    "id": string;
    "name": string;
    "available": boolean;
    "roots": string[] | null;
    "found": string[] | null;
    "events": number;
}

/**
 * HarnessReport is one row of the per-harness report (settings page + scan-report tool).
 */
export interface HarnessReport {
    "id": string;
    "name": string;
    "available": boolean;
    "roots": string[] | null;
    "events": number;
    "sessions": number;
    "input": number;
    "output": number;
    "cacheRead": number;
    "cacheWrite": number;
    "reasoning": number;
    "total": number;
    "costUsd": number;
    "reportedCostUsd": number;
    "latencyRows": number;
    "ttftRows": number;
    "firstTs": number;
    "lastTs": number;
}

/**
 * HeatCell is one day of the activity heatmap.
 */
export interface HeatCell {
    "day": string;
    "total": number;
    "costUsd": number;
    "events": number;
}

/**
 * LatencyPoint is one event with timing, for the scatter/latency views.
 */
export interface LatencyPoint {
    "ts": number;
    "latencyMs": number;
    "ttftMs": number;
    "model": string;
    "harness": string;
    "total": number;
    "input": number;
    "output": number;
    "project": string;
    "sessionId": string;
}

/**
 * ModelPrice is one row of the price table.
 */
export interface ModelPrice {
    "modelKey": string;
    "inputPerM": number;
    "outputPerM": number;
    "cacheReadPerM": number;
    "cacheWritePerM": number;
    "source": string;
    "updatedAt": number;
}

/**
 * PriceRule is a per-model multiplier rule.
 */
export interface PriceRule {
    "modelKey": string;
    "inputMult": number;
    "outputMult": number;
    "cacheReadMult": number;
    "cacheWriteMult": number;
    "disabled": boolean;
}

/**
 * RangeQuery is the single filter struct shared by every read path.
 * FromMs is inclusive, ToMs is exclusive. Zero means unbounded.
 */
export interface RangeQuery {
    "fromMs": number;
    "toMs": number;
    "harness": string[] | null;
    "models": string[] | null;
    "projects": string[] | null;
    "agentTypes": string[] | null;
    "outcomes": string[] | null;
    "costSources": string[] | null;

    /**
     * SessionIDs restricts the query to specific sessions. It forces the event source,
     * because neither daily rollup carries a session dimension.
     */
    "sessionIds": string[] | null;
}

/**
 * RealtimeSnapshot is the realtime view payload.
 */
export interface RealtimeSnapshot {
    "windowMinutes": number;

    /**
     * one point per minute
     */
    "buckets": SeriesPoint[] | null;

    /**
     * seen in the last 5 minutes
     */
    "activeSessions": SessionRow[] | null;
    "byModel": BreakdownRow[] | null;
    "latency": LatencyPoint[] | null;
    "totals": Totals;
}

/**
 * ScanRoot is a user-configured extra root.
 */
export interface ScanRoot {
    "harness": string;
    "path": string;
    "exists": boolean;
}

/**
 * SeriesPoint is one bucket of a time series (a day, or a group key).
 * Key is a local day (YYYY-MM-DD) for day series, an ISO week (YYYY-Www) or month
 * (YYYY-MM) for the coarser buckets, and an epoch-millisecond string for hour and minute
 * buckets; the frontend formats the last two in the configured timezone.
 */
export interface SeriesPoint {
    "key": string;
    "input": number;
    "output": number;
    "cacheRead": number;
    "cacheWrite": number;
    "reasoning": number;
    "total": number;
    "costUsd": number;
    "events": number;
}

/**
 * SeriesResult is a time series together with the bucket size it was actually built at.
 * The store may answer more coarsely than asked when the range would produce a chart no
 * one can read, so the caller renders the granularity it was given, not the one it asked
 * for.
 */
export interface SeriesResult {
    "granularity": string;
    "points": SeriesPoint[] | null;
}

/**
 * Session is one harness session's identity and static metadata.
 */
export interface Session {
    "Harness": string;
    "SessionID": string;
    "ParentSessionID": string;
    "Project": string;
    "Model": string;
    "AgentType": string;
    "AgentName": string;
    "SourceFile": string;
    "StartedAt": number;
    "UpdatedAt": number;
}

/**
 * SessionPage is a paged slice of sessions and the total matching count.
 */
export interface SessionPage {
    "rows": SessionRow[] | null;
    "total": number;
}

/**
 * SessionRow is one row of the sessions page. Token/cost columns are lifetime sums
 * for the session; the range filter selects sessions active in the range.
 */
export interface SessionRow {
    "harness": string;
    "sessionId": string;
    "project": string;
    "model": string;
    "agentType": string;
    "agentName": string;
    "startedAt": number;
    "updatedAt": number;
    "events": number;
    "input": number;
    "output": number;
    "cacheRead": number;
    "cacheWrite": number;
    "reasoning": number;
    "total": number;
    "costUsd": number;
    "latencyAvgMs": number;
    "latencyCount": number;
}

/**
 * Settings is the persisted, user-editable configuration.
 */
export interface Settings {
    "tz": string;
    "idleIntervalSeconds": number;
    "burstIntervalSeconds": number;
    "burstWindowSeconds": number;
    "concurrency": number;
    "autoSyncPrices": boolean;
    "lastPriceSync": number;
    "serverHost": string;
    "serverPort": number;
    "theme": string;
    "locale": string;
}

/**
 * SettingsPatch is a partial settings update; empty/zero fields are ignored.
 */
export interface SettingsPatch {
    "tz": string;
    "idleIntervalSeconds": number;
    "burstIntervalSeconds": number;
    "concurrency": number;
    "autoSyncPrices": boolean | null;
    "serverHost": string;
    "serverPort": number;
    "theme": string;
    "locale": string;
}

/**
 * StackedPoint is one (day, dimension value) cell of a stacked series.
 */
export interface StackedPoint {
    "day": string;
    "key": string;
    "total": number;
    "costUsd": number;
    "events": number;
}

/**
 * Stats describes the local database.
 */
export interface Stats {
    "dbPath": string;
    "dbBytes": number;
    "events": number;
    "sessions": number;
    "firstTs": number;
    "lastTs": number;
    "unpricedModels": number;
    "syncRuns": number;
}

/**
 * SyncRun is one recorded sync execution.
 */
export interface SyncRun {
    "id": number;
    "startedAt": number;
    "finishedAt": number;
    "trigger": string;
    "filesWalked": number;
    "filesChanged": number;
    "eventsInserted": number;
    "eventsUpdated": number;
    "durationMs": number;
    "error": string;
}

/**
 * Totals is an aggregate over a range.
 */
export interface Totals {
    "events": number;
    "input": number;
    "output": number;
    "cacheRead": number;
    "cacheWrite": number;
    "reasoning": number;
    "total": number;
    "costUsd": number;

    /**
     * ReportedCostUSD is the part of CostUSD the source itself reported (as opposed
     * to a price-table estimate), so the UI can show coverage.
     */
    "reportedCostUsd": number;
    "costUnavailable": number;
    "latencySumMs": number;
    "latencyCount": number;
    "ttftSumMs": number;
    "ttftCount": number;
}
