// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AdapterState is the per-harness outcome of a scan.
 */
export interface AdapterState {
    "id": string;
    "available": boolean;
    "skipped": boolean;
    "full": boolean;
    "events": number;
    "error": string;
}

/**
 * DataChangedEvent is the payload of EventData: an empty signal meaning "refetch what you
 * are showing". It exists as a named type so the generated bindings stay typed.
 */
export interface DataChangedEvent {
}

/**
 * DoneEvent is the payload of EventDone.
 */
export interface DoneEvent {
    "trigger": string;
    "filesWalked": number;
    "filesChanged": number;
    "eventsInserted": number;
    "eventsUpdated": number;
    "durationMs": number;
    "cold": boolean;
}

/**
 * ErrorEvent is the payload of EventError.
 */
export interface ErrorEvent {
    "harness": string;
    "message": string;
}

/**
 * ProgressEvent is the payload of EventProgress.
 */
export interface ProgressEvent {
    "harness": string;
    "phase": string;
    "walked": number;
    "changed": number;
    "events": number;
    "elapsedMs": number;
}

/**
 * RunSummary describes one completed scan.
 */
export interface RunSummary {
    "startedAt": number;
    "finishedAt": number;
    "trigger": string;
    "filesWalked": number;
    "filesChanged": number;
    "eventsInserted": number;
    "eventsUpdated": number;
    "durationMs": number;
    "cold": boolean;
    "harnesses": AdapterState[] | null;
    "error": string;
}

/**
 * StateEvent is the payload of EventState. It is the only event the frontend needs to know
 * whether a scan is in flight; intervals and the next run time come from the sync service,
 * which owns the schedule.
 */
export interface StateEvent {
    "running": boolean;
    "trigger": string;
}
