// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * EventsService serves the raw event table and its export.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../store/models.js";

/**
 * Columns returns the column names available for the export and the column settings modal.
 */
export function Columns(): $CancellablePromise<string[] | null> {
    return $Call.ByID(3963644866);
}

/**
 * Export renders the filtered events as CSV or JSON. The content is returned rather than
 * written to a file so export also works in headless server mode, where native save
 * dialogs do not exist; the frontend turns it into a download.
 */
export function Export(q: store$0.RangeQuery, format: string): $CancellablePromise<store$0.ExportResult> {
    return $Call.ByID(546539813, q, format);
}

/**
 * List returns a page of events, newest first, with the total match count.
 */
export function List(q: store$0.RangeQuery, offset: number, limit: number): $CancellablePromise<store$0.EventPage> {
    return $Call.ByID(1830809055, q, offset, limit);
}
