// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MetaService serves the dimensions the UI filters by: harnesses, facet values, sessions.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../store/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Facets lists the distinct values of a dimension with their totals, for filter menus.
 * Accepted dimensions: harness, model, project, agentType, outcome, costSource.
 */
export function Facets(dim: string): $CancellablePromise<store$0.FacetValue[] | null> {
    return $Call.ByID(614407539, dim);
}

/**
 * Harnesses lists every known harness with its availability and resolved roots.
 */
export function Harnesses(): $CancellablePromise<store$0.HarnessInfo[] | null> {
    return $Call.ByID(3941692745);
}

/**
 * RunReport returns the per-harness report (roots, availability, and what each harness
 * contributed). It is the same data the scan-report tool prints.
 */
export function RunReport(): $CancellablePromise<store$0.HarnessReport[] | null> {
    return $Call.ByID(2795832110);
}

/**
 * SessionDetail returns a session's identity, its lifetime totals and its model mix.
 */
export function SessionDetail(harness: string, sessionID: string): $CancellablePromise<$models.SessionDetail> {
    return $Call.ByID(3145524020, harness, sessionID);
}

/**
 * Sessions returns a page of sessions. The range filter selects sessions active inside it;
 * the token and cost columns are lifetime sums for each session.
 */
export function Sessions(q: store$0.RangeQuery, offset: number, limit: number, sortBy: string): $CancellablePromise<store$0.SessionPage> {
    return $Call.ByID(3567951874, q, offset, limit, sortBy);
}
