// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService owns everything the user can change: scan roots, intervals, timezone,
 * prices and price rules, and the destructive reset.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as pricing$0 from "../pricing/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../store/models.js";

/**
 * AddScanRoot registers an extra root and immediately scans it, so its data appears
 * without waiting for the next scheduled pass.
 */
export function AddScanRoot(harness: string, path: string): $CancellablePromise<store$0.ScanRoot[] | null> {
    return $Call.ByID(2218397319, harness, path);
}

/**
 * DeleteAllData wipes every derived row. The next scan rebuilds from the session files,
 * which are never modified.
 */
export function DeleteAllData(): $CancellablePromise<void> {
    return $Call.ByID(71445891);
}

/**
 * DeletePrice removes a price row.
 */
export function DeletePrice(modelKey: string): $CancellablePromise<store$0.ModelPrice[] | null> {
    return $Call.ByID(2776984229, modelKey);
}

/**
 * Get returns the effective settings: persisted values where present, otherwise the
 * process defaults.
 */
export function Get(): $CancellablePromise<store$0.Settings> {
    return $Call.ByID(1734258469);
}

/**
 * PriceRules lists the per-model multipliers.
 */
export function PriceRules(): $CancellablePromise<store$0.PriceRule[] | null> {
    return $Call.ByID(3811093659);
}

/**
 * Prices lists the price table.
 */
export function Prices(): $CancellablePromise<store$0.ModelPrice[] | null> {
    return $Call.ByID(1859368613);
}

/**
 * RecalculateCosts re-prices every event whose cost came from the price table.
 */
export function RecalculateCosts(): $CancellablePromise<number> {
    return $Call.ByID(1009527024);
}

/**
 * RemoveScanRoot forgets an extra root.
 */
export function RemoveScanRoot(harness: string, path: string): $CancellablePromise<store$0.ScanRoot[] | null> {
    return $Call.ByID(2675384762, harness, path);
}

/**
 * ScanRoots lists the user-added extra roots for every harness.
 */
export function ScanRoots(): $CancellablePromise<store$0.ScanRoot[] | null> {
    return $Call.ByID(701075751);
}

/**
 * SetPrice writes a manual price. A manual row is never overwritten by a catalog sync.
 */
export function SetPrice(p: store$0.ModelPrice): $CancellablePromise<store$0.ModelPrice[] | null> {
    return $Call.ByID(1564978846, p);
}

/**
 * SetPriceRule writes a per-model multiplier rule.
 */
export function SetPriceRule(r: store$0.PriceRule): $CancellablePromise<store$0.PriceRule[] | null> {
    return $Call.ByID(3547341448, r);
}

/**
 * Stats returns the database summary shown on the settings page.
 */
export function Stats(): $CancellablePromise<store$0.Stats> {
    return $Call.ByID(791992342);
}

/**
 * SyncPrices downloads a price catalog and re-prices every estimated event.
 * 
 * A failure here is reported to the caller but is not fatal to the application: with no
 * catalog the affected events stay "unavailable" and the UI shows a dash.
 */
export function SyncPrices(source: string): $CancellablePromise<pricing$0.SyncResult> {
    return $Call.ByID(2650749070, source);
}

/**
 * Update applies a partial settings change and returns the new effective settings.
 * 
 * A timezone change is not a cosmetic edit: every event's local day bucket and therefore
 * every rollup row is keyed on it, so the day buckets are rewritten and the rollups
 * rebuilt before the call returns. The frontend shows a rebuilding state for the duration.
 */
export function Update(patch: store$0.SettingsPatch): $CancellablePromise<store$0.Settings> {
    return $Call.ByID(2113218410, patch);
}
