// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * HeldSpec is the JSON view of the currently held assertions.
 */
export interface HeldSpec {
    "system": boolean;
    "display": boolean;
    "lid": boolean;
}

/**
 * LidState separates a successful private lid request from the observed shared policy.
 * Known=false means the effective policy could not be read, not that sleep is blocked.
 */
export interface LidState {
    "privateApi": boolean;
    "requested": boolean;
    "known": boolean;
    "effective": boolean;
}

/**
 * Status is the controller's externally visible state. Every field is JSON-safe and
 * comparable, so the service can hand it straight to the frontend and the controller can
 * cheaply detect a change before emitting an event.
 */
export interface Status {
    "mode": string;
    "supported": boolean;
    "keepingAwake": boolean;
    "lidSupported": boolean;
    "lidControl": LidState;
    "active": boolean;
    "activeSessions": number;
    "agents": string;
    "lastWriteMs": number;
    "idleMs": number;
    "sleepAtMs": number;
    "held": HeldSpec;
    "clamshell": boolean;

    /**
     * Detail names the current phase: disabled, unsupported, always, active, grace,
     * waiting-user, sleeping, blocked or idle. It is meant for a status line, not for logic.
     */
    "detail": string;
    "error": string;
}
